name: Lab01 Variables and Secrets
run-name: Lab01 - ${{ github.actor }} is testing variables and secrets 🚀
permissions: read-all
on:
  workflow_dispatch:
env:
  MY_VARIABLE: "Hello, GitHub Actions!"
jobs:
  demo-variables-and-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Print Variable
        run: |
          echo "The value of MY_VARIABLE is: $MY_VARIABLE"

      - name: Print Secret
        run: |
          echo "The value of DEMO_SECRET is: ${{ secrets.DEMO_SECRET }}"
